// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QuestionList.proto

public final class QuestionListProtos {
  private QuestionListProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QuestionListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:quizapi.questionlist.QuestionList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, bool&gt; Questions = 1;</code>
     */
    int getQuestionsCount();
    /**
     * <code>map&lt;string, bool&gt; Questions = 1;</code>
     */
    boolean containsQuestions(
        java.lang.String key);
    /**
     * Use {@link #getQuestionsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.Boolean>
    getQuestions();
    /**
     * <code>map&lt;string, bool&gt; Questions = 1;</code>
     */
    java.util.Map<java.lang.String, java.lang.Boolean>
    getQuestionsMap();
    /**
     * <code>map&lt;string, bool&gt; Questions = 1;</code>
     */

    boolean getQuestionsOrDefault(
        java.lang.String key,
        boolean defaultValue);
    /**
     * <code>map&lt;string, bool&gt; Questions = 1;</code>
     */

    boolean getQuestionsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code quizapi.questionlist.QuestionList}
   */
  public static final class QuestionList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:quizapi.questionlist.QuestionList)
      QuestionListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QuestionList.newBuilder() to construct.
    private QuestionList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QuestionList() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new QuestionList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QuestionList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                questions_ = com.google.protobuf.MapField.newMapField(
                    QuestionsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Boolean>
              questions__ = input.readMessage(
                  QuestionsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              questions_.getMutableMap().put(
                  questions__.getKey(), questions__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return QuestionListProtos.internal_static_quizapi_questionlist_QuestionList_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetQuestions();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return QuestionListProtos.internal_static_quizapi_questionlist_QuestionList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QuestionListProtos.QuestionList.class, QuestionListProtos.QuestionList.Builder.class);
    }

    public static final int QUESTIONS_FIELD_NUMBER = 1;
    private static final class QuestionsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.Boolean> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.Boolean>newDefaultInstance(
                  QuestionListProtos.internal_static_quizapi_questionlist_QuestionList_QuestionsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.BOOL,
                  false);
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Boolean> questions_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Boolean>
    internalGetQuestions() {
      if (questions_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            QuestionsDefaultEntryHolder.defaultEntry);
      }
      return questions_;
    }

    public int getQuestionsCount() {
      return internalGetQuestions().getMap().size();
    }
    /**
     * <code>map&lt;string, bool&gt; Questions = 1;</code>
     */

    @java.lang.Override
    public boolean containsQuestions(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetQuestions().getMap().containsKey(key);
    }
    /**
     * Use {@link #getQuestionsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Boolean> getQuestions() {
      return getQuestionsMap();
    }
    /**
     * <code>map&lt;string, bool&gt; Questions = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.Boolean> getQuestionsMap() {
      return internalGetQuestions().getMap();
    }
    /**
     * <code>map&lt;string, bool&gt; Questions = 1;</code>
     */
    @java.lang.Override

    public boolean getQuestionsOrDefault(
        java.lang.String key,
        boolean defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Boolean> map =
          internalGetQuestions().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, bool&gt; Questions = 1;</code>
     */
    @java.lang.Override

    public boolean getQuestionsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Boolean> map =
          internalGetQuestions().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetQuestions(),
          QuestionsDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.Boolean> entry
           : internalGetQuestions().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Boolean>
        questions__ = QuestionsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, questions__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof QuestionListProtos.QuestionList)) {
        return super.equals(obj);
      }
      QuestionListProtos.QuestionList other = (QuestionListProtos.QuestionList) obj;

      if (!internalGetQuestions().equals(
          other.internalGetQuestions())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetQuestions().getMap().isEmpty()) {
        hash = (37 * hash) + QUESTIONS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetQuestions().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static QuestionListProtos.QuestionList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QuestionListProtos.QuestionList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QuestionListProtos.QuestionList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QuestionListProtos.QuestionList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QuestionListProtos.QuestionList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QuestionListProtos.QuestionList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QuestionListProtos.QuestionList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QuestionListProtos.QuestionList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static QuestionListProtos.QuestionList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static QuestionListProtos.QuestionList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static QuestionListProtos.QuestionList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QuestionListProtos.QuestionList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(QuestionListProtos.QuestionList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code quizapi.questionlist.QuestionList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:quizapi.questionlist.QuestionList)
        QuestionListProtos.QuestionListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return QuestionListProtos.internal_static_quizapi_questionlist_QuestionList_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetQuestions();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableQuestions();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return QuestionListProtos.internal_static_quizapi_questionlist_QuestionList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                QuestionListProtos.QuestionList.class, QuestionListProtos.QuestionList.Builder.class);
      }

      // Construct using QuestionListProtos.QuestionList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableQuestions().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return QuestionListProtos.internal_static_quizapi_questionlist_QuestionList_descriptor;
      }

      @java.lang.Override
      public QuestionListProtos.QuestionList getDefaultInstanceForType() {
        return QuestionListProtos.QuestionList.getDefaultInstance();
      }

      @java.lang.Override
      public QuestionListProtos.QuestionList build() {
        QuestionListProtos.QuestionList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public QuestionListProtos.QuestionList buildPartial() {
        QuestionListProtos.QuestionList result = new QuestionListProtos.QuestionList(this);
        int from_bitField0_ = bitField0_;
        result.questions_ = internalGetQuestions();
        result.questions_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof QuestionListProtos.QuestionList) {
          return mergeFrom((QuestionListProtos.QuestionList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(QuestionListProtos.QuestionList other) {
        if (other == QuestionListProtos.QuestionList.getDefaultInstance()) return this;
        internalGetMutableQuestions().mergeFrom(
            other.internalGetQuestions());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        QuestionListProtos.QuestionList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (QuestionListProtos.QuestionList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.Boolean> questions_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.Boolean>
      internalGetQuestions() {
        if (questions_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              QuestionsDefaultEntryHolder.defaultEntry);
        }
        return questions_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.Boolean>
      internalGetMutableQuestions() {
        onChanged();;
        if (questions_ == null) {
          questions_ = com.google.protobuf.MapField.newMapField(
              QuestionsDefaultEntryHolder.defaultEntry);
        }
        if (!questions_.isMutable()) {
          questions_ = questions_.copy();
        }
        return questions_;
      }

      public int getQuestionsCount() {
        return internalGetQuestions().getMap().size();
      }
      /**
       * <code>map&lt;string, bool&gt; Questions = 1;</code>
       */

      @java.lang.Override
      public boolean containsQuestions(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetQuestions().getMap().containsKey(key);
      }
      /**
       * Use {@link #getQuestionsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Boolean> getQuestions() {
        return getQuestionsMap();
      }
      /**
       * <code>map&lt;string, bool&gt; Questions = 1;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.Boolean> getQuestionsMap() {
        return internalGetQuestions().getMap();
      }
      /**
       * <code>map&lt;string, bool&gt; Questions = 1;</code>
       */
      @java.lang.Override

      public boolean getQuestionsOrDefault(
          java.lang.String key,
          boolean defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Boolean> map =
            internalGetQuestions().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, bool&gt; Questions = 1;</code>
       */
      @java.lang.Override

      public boolean getQuestionsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Boolean> map =
            internalGetQuestions().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearQuestions() {
        internalGetMutableQuestions().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, bool&gt; Questions = 1;</code>
       */

      public Builder removeQuestions(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableQuestions().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Boolean>
      getMutableQuestions() {
        return internalGetMutableQuestions().getMutableMap();
      }
      /**
       * <code>map&lt;string, bool&gt; Questions = 1;</code>
       */
      public Builder putQuestions(
          java.lang.String key,
          boolean value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        
        internalGetMutableQuestions().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, bool&gt; Questions = 1;</code>
       */

      public Builder putAllQuestions(
          java.util.Map<java.lang.String, java.lang.Boolean> values) {
        internalGetMutableQuestions().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:quizapi.questionlist.QuestionList)
    }

    // @@protoc_insertion_point(class_scope:quizapi.questionlist.QuestionList)
    private static final QuestionListProtos.QuestionList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new QuestionListProtos.QuestionList();
    }

    public static QuestionListProtos.QuestionList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QuestionList>
        PARSER = new com.google.protobuf.AbstractParser<QuestionList>() {
      @java.lang.Override
      public QuestionList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QuestionList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QuestionList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QuestionList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public QuestionListProtos.QuestionList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_quizapi_questionlist_QuestionList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_quizapi_questionlist_QuestionList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_quizapi_questionlist_QuestionList_QuestionsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_quizapi_questionlist_QuestionList_QuestionsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022QuestionList.proto\022\024quizapi.questionli" +
      "st\"\206\001\n\014QuestionList\022D\n\tQuestions\030\001 \003(\01321" +
      ".quizapi.questionlist.QuestionList.Quest" +
      "ionsEntry\0320\n\016QuestionsEntry\022\013\n\003key\030\001 \001(\t" +
      "\022\r\n\005value\030\002 \001(\010:\0028\001B\026\n\000B\022QuestionListPro" +
      "tosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_quizapi_questionlist_QuestionList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_quizapi_questionlist_QuestionList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_quizapi_questionlist_QuestionList_descriptor,
        new java.lang.String[] { "Questions", });
    internal_static_quizapi_questionlist_QuestionList_QuestionsEntry_descriptor =
      internal_static_quizapi_questionlist_QuestionList_descriptor.getNestedTypes().get(0);
    internal_static_quizapi_questionlist_QuestionList_QuestionsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_quizapi_questionlist_QuestionList_QuestionsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
