package cc.nosharp.quizapi.datamodels;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QuestionList.proto

public final class QuestionListProtos {
  private QuestionListProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QuestionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:quizapi.questionlist.Question)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string Question = 1;</code>
     * @return Whether the question field is set.
     */
    boolean hasQuestion();
    /**
     * <code>required string Question = 1;</code>
     * @return The question.
     */
    java.lang.String getQuestion();
    /**
     * <code>required string Question = 1;</code>
     * @return The bytes for question.
     */
    com.google.protobuf.ByteString
        getQuestionBytes();

    /**
     * <code>required string Answer = 2;</code>
     * @return Whether the answer field is set.
     */
    boolean hasAnswer();
    /**
     * <code>required string Answer = 2;</code>
     * @return The answer.
     */
    java.lang.String getAnswer();
    /**
     * <code>required string Answer = 2;</code>
     * @return The bytes for answer.
     */
    com.google.protobuf.ByteString
        getAnswerBytes();
  }
  /**
   * Protobuf type {@code quizapi.questionlist.Question}
   */
  public static final class Question extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:quizapi.questionlist.Question)
      QuestionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Question.newBuilder() to construct.
    private Question(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Question() {
      question_ = "";
      answer_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Question();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Question(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              question_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              answer_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return QuestionListProtos.internal_static_quizapi_questionlist_Question_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return QuestionListProtos.internal_static_quizapi_questionlist_Question_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QuestionListProtos.Question.class, QuestionListProtos.Question.Builder.class);
    }

    private int bitField0_;
    public static final int QUESTION_FIELD_NUMBER = 1;
    private volatile java.lang.Object question_;
    /**
     * <code>required string Question = 1;</code>
     * @return Whether the question field is set.
     */
    @java.lang.Override
    public boolean hasQuestion() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string Question = 1;</code>
     * @return The question.
     */
    @java.lang.Override
    public java.lang.String getQuestion() {
      java.lang.Object ref = question_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          question_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Question = 1;</code>
     * @return The bytes for question.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getQuestionBytes() {
      java.lang.Object ref = question_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        question_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ANSWER_FIELD_NUMBER = 2;
    private volatile java.lang.Object answer_;
    /**
     * <code>required string Answer = 2;</code>
     * @return Whether the answer field is set.
     */
    @java.lang.Override
    public boolean hasAnswer() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string Answer = 2;</code>
     * @return The answer.
     */
    @java.lang.Override
    public java.lang.String getAnswer() {
      java.lang.Object ref = answer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          answer_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Answer = 2;</code>
     * @return The bytes for answer.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAnswerBytes() {
      java.lang.Object ref = answer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        answer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasQuestion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAnswer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, question_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, answer_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, question_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, answer_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof QuestionListProtos.Question)) {
        return super.equals(obj);
      }
      QuestionListProtos.Question other = (QuestionListProtos.Question) obj;

      if (hasQuestion() != other.hasQuestion()) return false;
      if (hasQuestion()) {
        if (!getQuestion()
            .equals(other.getQuestion())) return false;
      }
      if (hasAnswer() != other.hasAnswer()) return false;
      if (hasAnswer()) {
        if (!getAnswer()
            .equals(other.getAnswer())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasQuestion()) {
        hash = (37 * hash) + QUESTION_FIELD_NUMBER;
        hash = (53 * hash) + getQuestion().hashCode();
      }
      if (hasAnswer()) {
        hash = (37 * hash) + ANSWER_FIELD_NUMBER;
        hash = (53 * hash) + getAnswer().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static QuestionListProtos.Question parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QuestionListProtos.Question parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QuestionListProtos.Question parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QuestionListProtos.Question parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QuestionListProtos.Question parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QuestionListProtos.Question parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QuestionListProtos.Question parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QuestionListProtos.Question parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static QuestionListProtos.Question parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static QuestionListProtos.Question parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static QuestionListProtos.Question parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QuestionListProtos.Question parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(QuestionListProtos.Question prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code quizapi.questionlist.Question}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:quizapi.questionlist.Question)
        QuestionListProtos.QuestionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return QuestionListProtos.internal_static_quizapi_questionlist_Question_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return QuestionListProtos.internal_static_quizapi_questionlist_Question_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                QuestionListProtos.Question.class, QuestionListProtos.Question.Builder.class);
      }

      // Construct using QuestionListProtos.Question.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        question_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        answer_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return QuestionListProtos.internal_static_quizapi_questionlist_Question_descriptor;
      }

      @java.lang.Override
      public QuestionListProtos.Question getDefaultInstanceForType() {
        return QuestionListProtos.Question.getDefaultInstance();
      }

      @java.lang.Override
      public QuestionListProtos.Question build() {
        QuestionListProtos.Question result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public QuestionListProtos.Question buildPartial() {
        QuestionListProtos.Question result = new QuestionListProtos.Question(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.question_ = question_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.answer_ = answer_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof QuestionListProtos.Question) {
          return mergeFrom((QuestionListProtos.Question)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(QuestionListProtos.Question other) {
        if (other == QuestionListProtos.Question.getDefaultInstance()) return this;
        if (other.hasQuestion()) {
          bitField0_ |= 0x00000001;
          question_ = other.question_;
          onChanged();
        }
        if (other.hasAnswer()) {
          bitField0_ |= 0x00000002;
          answer_ = other.answer_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasQuestion()) {
          return false;
        }
        if (!hasAnswer()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        QuestionListProtos.Question parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (QuestionListProtos.Question) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object question_ = "";
      /**
       * <code>required string Question = 1;</code>
       * @return Whether the question field is set.
       */
      public boolean hasQuestion() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string Question = 1;</code>
       * @return The question.
       */
      public java.lang.String getQuestion() {
        java.lang.Object ref = question_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            question_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string Question = 1;</code>
       * @return The bytes for question.
       */
      public com.google.protobuf.ByteString
          getQuestionBytes() {
        java.lang.Object ref = question_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          question_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Question = 1;</code>
       * @param value The question to set.
       * @return This builder for chaining.
       */
      public Builder setQuestion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        question_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Question = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuestion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        question_ = getDefaultInstance().getQuestion();
        onChanged();
        return this;
      }
      /**
       * <code>required string Question = 1;</code>
       * @param value The bytes for question to set.
       * @return This builder for chaining.
       */
      public Builder setQuestionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        question_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object answer_ = "";
      /**
       * <code>required string Answer = 2;</code>
       * @return Whether the answer field is set.
       */
      public boolean hasAnswer() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string Answer = 2;</code>
       * @return The answer.
       */
      public java.lang.String getAnswer() {
        java.lang.Object ref = answer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            answer_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string Answer = 2;</code>
       * @return The bytes for answer.
       */
      public com.google.protobuf.ByteString
          getAnswerBytes() {
        java.lang.Object ref = answer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          answer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Answer = 2;</code>
       * @param value The answer to set.
       * @return This builder for chaining.
       */
      public Builder setAnswer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        answer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Answer = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAnswer() {
        bitField0_ = (bitField0_ & ~0x00000002);
        answer_ = getDefaultInstance().getAnswer();
        onChanged();
        return this;
      }
      /**
       * <code>required string Answer = 2;</code>
       * @param value The bytes for answer to set.
       * @return This builder for chaining.
       */
      public Builder setAnswerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        answer_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:quizapi.questionlist.Question)
    }

    // @@protoc_insertion_point(class_scope:quizapi.questionlist.Question)
    private static final QuestionListProtos.Question DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new QuestionListProtos.Question();
    }

    public static QuestionListProtos.Question getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Question>
        PARSER = new com.google.protobuf.AbstractParser<Question>() {
      @java.lang.Override
      public Question parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Question(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Question> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Question> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public QuestionListProtos.Question getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QuestionListProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:quizapi.questionlist.QuestionListProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
     */
    java.util.List<QuestionListProtos.Question> 
        getQuestionsList();
    /**
     * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
     */
    QuestionListProtos.Question getQuestions(int index);
    /**
     * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
     */
    int getQuestionsCount();
    /**
     * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
     */
    java.util.List<? extends QuestionListProtos.QuestionOrBuilder> 
        getQuestionsOrBuilderList();
    /**
     * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
     */
    QuestionListProtos.QuestionOrBuilder getQuestionsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code quizapi.questionlist.QuestionListProto}
   */
  public static final class QuestionListProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:quizapi.questionlist.QuestionListProto)
      QuestionListProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QuestionListProto.newBuilder() to construct.
    private QuestionListProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QuestionListProto() {
      questions_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new QuestionListProto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QuestionListProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                questions_ = new java.util.ArrayList<QuestionListProtos.Question>();
                mutable_bitField0_ |= 0x00000001;
              }
              questions_.add(
                  input.readMessage(QuestionListProtos.Question.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          questions_ = java.util.Collections.unmodifiableList(questions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return QuestionListProtos.internal_static_quizapi_questionlist_QuestionListProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return QuestionListProtos.internal_static_quizapi_questionlist_QuestionListProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QuestionListProtos.QuestionListProto.class, QuestionListProtos.QuestionListProto.Builder.class);
    }

    public static final int QUESTIONS_FIELD_NUMBER = 1;
    private java.util.List<QuestionListProtos.Question> questions_;
    /**
     * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
     */
    @java.lang.Override
    public java.util.List<QuestionListProtos.Question> getQuestionsList() {
      return questions_;
    }
    /**
     * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends QuestionListProtos.QuestionOrBuilder> 
        getQuestionsOrBuilderList() {
      return questions_;
    }
    /**
     * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
     */
    @java.lang.Override
    public int getQuestionsCount() {
      return questions_.size();
    }
    /**
     * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
     */
    @java.lang.Override
    public QuestionListProtos.Question getQuestions(int index) {
      return questions_.get(index);
    }
    /**
     * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
     */
    @java.lang.Override
    public QuestionListProtos.QuestionOrBuilder getQuestionsOrBuilder(
        int index) {
      return questions_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getQuestionsCount(); i++) {
        if (!getQuestions(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < questions_.size(); i++) {
        output.writeMessage(1, questions_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < questions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, questions_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof QuestionListProtos.QuestionListProto)) {
        return super.equals(obj);
      }
      QuestionListProtos.QuestionListProto other = (QuestionListProtos.QuestionListProto) obj;

      if (!getQuestionsList()
          .equals(other.getQuestionsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getQuestionsCount() > 0) {
        hash = (37 * hash) + QUESTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getQuestionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static QuestionListProtos.QuestionListProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QuestionListProtos.QuestionListProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QuestionListProtos.QuestionListProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QuestionListProtos.QuestionListProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QuestionListProtos.QuestionListProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QuestionListProtos.QuestionListProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QuestionListProtos.QuestionListProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QuestionListProtos.QuestionListProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static QuestionListProtos.QuestionListProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static QuestionListProtos.QuestionListProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static QuestionListProtos.QuestionListProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QuestionListProtos.QuestionListProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(QuestionListProtos.QuestionListProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code quizapi.questionlist.QuestionListProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:quizapi.questionlist.QuestionListProto)
        QuestionListProtos.QuestionListProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return QuestionListProtos.internal_static_quizapi_questionlist_QuestionListProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return QuestionListProtos.internal_static_quizapi_questionlist_QuestionListProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                QuestionListProtos.QuestionListProto.class, QuestionListProtos.QuestionListProto.Builder.class);
      }

      // Construct using QuestionListProtos.QuestionListProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getQuestionsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (questionsBuilder_ == null) {
          questions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          questionsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return QuestionListProtos.internal_static_quizapi_questionlist_QuestionListProto_descriptor;
      }

      @java.lang.Override
      public QuestionListProtos.QuestionListProto getDefaultInstanceForType() {
        return QuestionListProtos.QuestionListProto.getDefaultInstance();
      }

      @java.lang.Override
      public QuestionListProtos.QuestionListProto build() {
        QuestionListProtos.QuestionListProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public QuestionListProtos.QuestionListProto buildPartial() {
        QuestionListProtos.QuestionListProto result = new QuestionListProtos.QuestionListProto(this);
        int from_bitField0_ = bitField0_;
        if (questionsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            questions_ = java.util.Collections.unmodifiableList(questions_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.questions_ = questions_;
        } else {
          result.questions_ = questionsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof QuestionListProtos.QuestionListProto) {
          return mergeFrom((QuestionListProtos.QuestionListProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(QuestionListProtos.QuestionListProto other) {
        if (other == QuestionListProtos.QuestionListProto.getDefaultInstance()) return this;
        if (questionsBuilder_ == null) {
          if (!other.questions_.isEmpty()) {
            if (questions_.isEmpty()) {
              questions_ = other.questions_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureQuestionsIsMutable();
              questions_.addAll(other.questions_);
            }
            onChanged();
          }
        } else {
          if (!other.questions_.isEmpty()) {
            if (questionsBuilder_.isEmpty()) {
              questionsBuilder_.dispose();
              questionsBuilder_ = null;
              questions_ = other.questions_;
              bitField0_ = (bitField0_ & ~0x00000001);
              questionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getQuestionsFieldBuilder() : null;
            } else {
              questionsBuilder_.addAllMessages(other.questions_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getQuestionsCount(); i++) {
          if (!getQuestions(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        QuestionListProtos.QuestionListProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (QuestionListProtos.QuestionListProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<QuestionListProtos.Question> questions_ =
        java.util.Collections.emptyList();
      private void ensureQuestionsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          questions_ = new java.util.ArrayList<QuestionListProtos.Question>(questions_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          QuestionListProtos.Question, QuestionListProtos.Question.Builder, QuestionListProtos.QuestionOrBuilder> questionsBuilder_;

      /**
       * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
       */
      public java.util.List<QuestionListProtos.Question> getQuestionsList() {
        if (questionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(questions_);
        } else {
          return questionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
       */
      public int getQuestionsCount() {
        if (questionsBuilder_ == null) {
          return questions_.size();
        } else {
          return questionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
       */
      public QuestionListProtos.Question getQuestions(int index) {
        if (questionsBuilder_ == null) {
          return questions_.get(index);
        } else {
          return questionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
       */
      public Builder setQuestions(
          int index, QuestionListProtos.Question value) {
        if (questionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQuestionsIsMutable();
          questions_.set(index, value);
          onChanged();
        } else {
          questionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
       */
      public Builder setQuestions(
          int index, QuestionListProtos.Question.Builder builderForValue) {
        if (questionsBuilder_ == null) {
          ensureQuestionsIsMutable();
          questions_.set(index, builderForValue.build());
          onChanged();
        } else {
          questionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
       */
      public Builder addQuestions(QuestionListProtos.Question value) {
        if (questionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQuestionsIsMutable();
          questions_.add(value);
          onChanged();
        } else {
          questionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
       */
      public Builder addQuestions(
          int index, QuestionListProtos.Question value) {
        if (questionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQuestionsIsMutable();
          questions_.add(index, value);
          onChanged();
        } else {
          questionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
       */
      public Builder addQuestions(
          QuestionListProtos.Question.Builder builderForValue) {
        if (questionsBuilder_ == null) {
          ensureQuestionsIsMutable();
          questions_.add(builderForValue.build());
          onChanged();
        } else {
          questionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
       */
      public Builder addQuestions(
          int index, QuestionListProtos.Question.Builder builderForValue) {
        if (questionsBuilder_ == null) {
          ensureQuestionsIsMutable();
          questions_.add(index, builderForValue.build());
          onChanged();
        } else {
          questionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
       */
      public Builder addAllQuestions(
          java.lang.Iterable<? extends QuestionListProtos.Question> values) {
        if (questionsBuilder_ == null) {
          ensureQuestionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, questions_);
          onChanged();
        } else {
          questionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
       */
      public Builder clearQuestions() {
        if (questionsBuilder_ == null) {
          questions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          questionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
       */
      public Builder removeQuestions(int index) {
        if (questionsBuilder_ == null) {
          ensureQuestionsIsMutable();
          questions_.remove(index);
          onChanged();
        } else {
          questionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
       */
      public QuestionListProtos.Question.Builder getQuestionsBuilder(
          int index) {
        return getQuestionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
       */
      public QuestionListProtos.QuestionOrBuilder getQuestionsOrBuilder(
          int index) {
        if (questionsBuilder_ == null) {
          return questions_.get(index);  } else {
          return questionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
       */
      public java.util.List<? extends QuestionListProtos.QuestionOrBuilder> 
           getQuestionsOrBuilderList() {
        if (questionsBuilder_ != null) {
          return questionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(questions_);
        }
      }
      /**
       * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
       */
      public QuestionListProtos.Question.Builder addQuestionsBuilder() {
        return getQuestionsFieldBuilder().addBuilder(
            QuestionListProtos.Question.getDefaultInstance());
      }
      /**
       * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
       */
      public QuestionListProtos.Question.Builder addQuestionsBuilder(
          int index) {
        return getQuestionsFieldBuilder().addBuilder(
            index, QuestionListProtos.Question.getDefaultInstance());
      }
      /**
       * <code>repeated .quizapi.questionlist.Question Questions = 1;</code>
       */
      public java.util.List<QuestionListProtos.Question.Builder> 
           getQuestionsBuilderList() {
        return getQuestionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          QuestionListProtos.Question, QuestionListProtos.Question.Builder, QuestionListProtos.QuestionOrBuilder> 
          getQuestionsFieldBuilder() {
        if (questionsBuilder_ == null) {
          questionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              QuestionListProtos.Question, QuestionListProtos.Question.Builder, QuestionListProtos.QuestionOrBuilder>(
                  questions_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          questions_ = null;
        }
        return questionsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:quizapi.questionlist.QuestionListProto)
    }

    // @@protoc_insertion_point(class_scope:quizapi.questionlist.QuestionListProto)
    private static final QuestionListProtos.QuestionListProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new QuestionListProtos.QuestionListProto();
    }

    public static QuestionListProtos.QuestionListProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<QuestionListProto>
        PARSER = new com.google.protobuf.AbstractParser<QuestionListProto>() {
      @java.lang.Override
      public QuestionListProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QuestionListProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QuestionListProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QuestionListProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public QuestionListProtos.QuestionListProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_quizapi_questionlist_Question_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_quizapi_questionlist_Question_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_quizapi_questionlist_QuestionListProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_quizapi_questionlist_QuestionListProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022QuestionList.proto\022\024quizapi.questionli" +
      "st\",\n\010Question\022\020\n\010Question\030\001 \002(\t\022\016\n\006Answ" +
      "er\030\002 \002(\t\"F\n\021QuestionListProto\0221\n\tQuestio" +
      "ns\030\001 \003(\0132\036.quizapi.questionlist.Question" +
      "B\026\n\000B\022QuestionListProtos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_quizapi_questionlist_Question_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_quizapi_questionlist_Question_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_quizapi_questionlist_Question_descriptor,
        new java.lang.String[] { "Question", "Answer", });
    internal_static_quizapi_questionlist_QuestionListProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_quizapi_questionlist_QuestionListProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_quizapi_questionlist_QuestionListProto_descriptor,
        new java.lang.String[] { "Questions", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
