# Credit to this article https://dev.to/ewefie/getting-started-with-github-actions-run-junit-5-tests-in-a-java-project-with-maven-20g4 for help with this.
name: test
on: [push]
jobs:
  test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - uses: actions/setup-java@v2
          with:
            distribution: 'adopt'
            java-version: '11'
          - uses: supercharge/redis-github-action@1.2.0
            with:
              redis-version: 6
        - uses: actions/cache@v2
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-
        - run: mvn -B test --file pom.xml
